---
- name: Update and install ansible needed packages
  hosts: all
  vars:
    package_name: "ansible-2.7.1"

  tasks:
    - name: update ansible
      yum:
        state: present
        name: "{{ package_name }}"


    - name: install python package
      shell: |
        pip install ovirt-engine-sdk-python==4.2.4

