---
- name: Remove HWADDR line from ifcfg-eth0 configuration file
  hosts: all
  vars:
    new_vm_name: icigna

  tasks:

   - name: Set Hostname "{{ new_vm_name }}"
     hostname:
        name: "{{ new_vm_name }}"
     become: true

