---
- name: Remove HWADDR line from ifcfg-eth0 configuration file
  hosts: all
  vars:
    new_vm_name: icigna

  tasks:

   - name: Set Hostname "{{ new_vm_name }}"
     hostname:
        name: "{{ new_vm_name }}"
     become: true

   - name: Install epel
     yum: name=epel-release state=latest

   - name: Install ovirt guest tools
     yum:
        name=ovirt-guest-agent-common
        state=latest

   - name: Start ovirt guest tools
     systemd:
        state=started
        name=ovirt-guest-agent


