---
- name: Update and install ansible needed packages
  hosts: all
  vars:
    package_name: "ansible-2.7.1"

  tasks:
    - name: update ansible
      yum:
        state: present
        name: "{{ package_name }}"

    - name: install libcurl-devel and libxml2-devel
      yum:
        state: present
        name:
        - libcurl-devel
        - libxml2-devel

    - name: install python package
      shell: |
        pip install ovirt-engine-sdk-python==4.2.4

