---
- name: Update and install ansible needed packages
  hosts: all
  vars:
    package_name: "ansible-2.7"

  tasks:
    - name: update ansible
      yum:
        state: present
        namne: "{{ package_name }}"

