---
- hosts: all
  remote_user: root
  vars:
    vm_name:
    template_name:
    description: "Test template"

  vars_files:
    - ovirt-engine-vars.yml

  pre_tasks:
    - name: Login to oVirt
      ovirt_auth:
        url: "{{ engine_url }}"
        username: "{{ username }}"
        password: "{{ password }}"
        insecure: "{{ engine_insecure | default(true) }}"
      tags:
        - always

  tasks:
   - name: Creating template
     ovirt_templates:
       cluster: Production
       auth: "{{ ovirt_auth }}"
       name: "{{ template_name}}" 
       vm: "{{ vm_name }}"
#       cpu_profile: Default
       description: "{{ description }}"
