---
- name: Install and start Apache HTTPD
  hosts: all
  vars:
    index_message: "This is your new apache server"
    index_image: ""

  tasks:
    - name: httpd package is present
      yum:
        name: httpd
        state: present
      become: true

    - name: httpd is started
      service:
        name: httpd
        state: restarted
        enabled: true
      become: true
